# Generated by Django 4.1.4 on 2023-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sprinkler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "diameter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Диаметр выходного отверстия d, мм",
                    ),
                ),
                (
                    "mu",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Коэффициент расхода насадка μ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ороситель",
                "verbose_name_plural": "Оросители",
                "ordering": ("diameter",),
            },
        ),
    ]
