# Generated by Django 4.1.4 on 2024-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="Pmax",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Максимальное рабочее давление, МПа",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="Pmin",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Минимальное рабочее давление, МПа",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k0",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k0",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k1",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k1",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k2",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k2",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k3",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k3",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k4",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k4",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="k5",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k5",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="diameter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Диаметр выходного отверстия d, мм",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="mu",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Коэффициент расхода насадка μ",
            ),
        ),
    ]
