# Generated by Django 4.1.4 on 2024-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0002_sprinkler_pmax_sprinkler_pmin_sprinkler_k0_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sprinkler",
            options={
                "ordering": ("pk",),
                "verbose_name": "Ороситель",
                "verbose_name_plural": "Оросители",
            },
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="otv_type",
            field=models.CharField(
                choices=[("water", "Вода"), ("foam", "Пена")],
                default="water",
                max_length=50,
                verbose_name="Тип ОТВ",
            ),
        ),
    ]
