# Generated by Django 4.1.4 on 2024-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0003_alter_sprinkler_options_sprinkler_otv_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="intensity_Pmax",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                editable=False,
                max_digits=8,
                null=True,
                verbose_name="Интенсивность на макс. рабочем давлении",
            ),
        ),
        migrations.AddField(
            model_name="sprinkler",
            name="intensity_Pmin",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                editable=False,
                max_digits=8,
                null=True,
                verbose_name="Интенсивность на мин. рабочем давлении",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="Pmax",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Макс. рабочее давление, МПа",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="Pmin",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Мин. рабочее давление, МПа",
            ),
        ),
    ]
