# Generated by Django 4.1.4 on 2024-08-25 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sprinkler",
            "0004_sprinkler_intensity_pmax_sprinkler_intensity_pmin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
                verbose_name="Группы помещений",
            ),
        ),
    ]
