# Generated by Django 4.1.4 on 2024-09-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0005_sprinkler_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="S",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="площадь орошения, м²",
            ),
        ),
    ]
