# Generated by Django 4.1.4 on 2024-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0006_sprinkler_s"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="thermal_lock",
            field=models.CharField(
                blank=True,
                choices=[("sprinkler", "Спринклерный"), ("drench", "Дренчерный")],
                default=str,
                max_length=100,
                verbose_name="Наличие теплового замка",
            ),
        ),
    ]
