# Generated by Django 4.1.4 on 2024-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0007_sprinkler_thermal_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="mounting_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vertical_up", "Вертикально вверх"),
                    ("vertical_down", "Вертикально вниз"),
                ],
                default=str,
                max_length=100,
                verbose_name="Монтажное положение",
            ),
        ),
    ]
