# Generated by Django 4.1.4 on 2024-09-22 13:20

from django.db import migrations

from sprinkler.models import MountingPositions, ThermalLocks


def update_sprinklers(apps, schema_editor):
    Sprinkler = apps.get_model("sprinkler", "Sprinkler")
    for s in Sprinkler.objects.all():
        if s.name[0] == "С" or any(map(lambda x: s.name.startswith(x), ("SSP", "SSU", "СОБР"))):
            s.thermal_lock = ThermalLocks.sprinkler
        elif s.name[0] == "Д" or any(map(lambda x: s.name.startswith(x), ("SP", "SU", "ОЦ", "ОЭ"))):
            s.thermal_lock = ThermalLocks.drench
        if s.name.split("-")[0][-1] == "В" or any(
            map(lambda x: s.name.startswith(x), ("SSU", "SU", "СУУ", "СВУ", "СОБР-В", "ОЦ", "ОЭ"))
        ):
            s.mounting_position = MountingPositions.vertical_up
        if s.name.split("-")[0][-1] == "Н" or any(
            map(lambda x: s.name.startswith(x), ("SSP", "SP", "СВК", "СУУ", "ДУУ", "СВУ", "ДВУ", "СОБР-Н", "ОЦ", "ОЭ"))
        ):
            s.mounting_position = MountingPositions.vertical_down
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0008_sprinkler_mounting_position"),
    ]

    operations = [migrations.RunPython(update_sprinklers, migrations.RunPython.noop)]
