# Generated by Django 4.1.4 on 2024-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0009_auto_20240922_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprinkler",
            name="k0",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k0",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="k1",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k1",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="k2",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k2",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="k3",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k3",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="k4",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k4",
            ),
        ),
        migrations.AlterField(
            model_name="sprinkler",
            name="k5",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k5",
            ),
        ),
    ]
