# Generated by Django 4.1.4 on 2025-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0010_alter_sprinkler_k0_alter_sprinkler_k1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="K",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Коэффициент производительности",
            ),
        ),
    ]
