# Generated by Django 4.1.4 on 2025-12-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprinkler", "0011_sprinkler_k"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinkler",
            name="k6",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="коэффициент k6",
            ),
        ),
    ]
