# Generated by Django 4.1.4 on 2025-07-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TubeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Тип трубы")),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_size",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Номинальный диаметр DN",
                    ),
                ),
                (
                    "ext_size",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Наружный диаметр, мм",
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Толщина стенки, мм",
                    ),
                ),
                (
                    "k_t",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Удельная характеристика Kт, л²/с²",
                    ),
                ),
                (
                    "tube_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="tubes.tubetype",
                        verbose_name="Тип трубы",
                    ),
                ),
            ],
        ),
    ]
