# Generated by Django 4.1.4 on 2025-12-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_calculateresults"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CalculateResults",
            new_name="CalculateResult",
        ),
    ]
