# Generated by Django 4.1.4 on 2025-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_calculateresults_calculateresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculateresult",
            name="data",
            field=models.JSONField(default=dict, verbose_name="Данные расчета"),
        ),
    ]
