# Generated by Django 4.1.4 on 2025-07-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlUnitName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование узла управления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=255, verbose_name="Обозначение узла управления"
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Диаметр узла управления, мм",
                    ),
                ),
                (
                    "dn",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="DN, мм"
                    ),
                ),
                (
                    "pressure_loss",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Коэффициент потерь давления",
                    ),
                ),
                (
                    "control_unit_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="management_node.controlunitname",
                        verbose_name="Наименование узла управления",
                    ),
                ),
            ],
        ),
    ]
