# Generated by Django 4.1.4 on 2025-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_node", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlunit",
            name="dn",
        ),
        migrations.AlterField(
            model_name="controlunit",
            name="diameter",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=10,
                verbose_name="Диаметр узла управления, DN, мм",
            ),
        ),
    ]
