# Generated by Django 4.1.4 on 2025-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_node", "0004_alter_controlunit_pressure_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlunit",
            name="pressure_loss",
            field=models.DecimalField(
                decimal_places=15,
                max_digits=15,
                verbose_name="Коэффициент потерь давления",
            ),
        ),
    ]
