# Generated by Django 4.1.4 on 2025-12-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_node", "0005_alter_controlunit_pressure_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlunit",
            name="installation_type",
            field=models.CharField(
                choices=[
                    ("sprinkler_water", "Спринклерная водозаполненная"),
                    ("sprinkler_air", "Спринклерная воздушная"),
                    ("drench", "Дренчерная"),
                ],
                default="sprinkler_water",
                max_length=50,
                verbose_name="Тип установки",
            ),
        ),
    ]
