# Generated by Django 4.1.4 on 2024-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_tags",
                    models.TextField(blank=True, default=str, verbose_name="META тэги"),
                ),
                (
                    "counters",
                    models.TextField(blank=True, default=str, verbose_name="Счетчики"),
                ),
            ],
            options={
                "verbose_name": "Настройки SEO",
                "verbose_name_plural": "Настройки SEO",
            },
        ),
    ]
